### ISSUE TITLE
Notification Sort

### ISSUE THREAD

**Issue by vilavlooi** [tb4mmaggots/eztots#4]
Sorting functionality not working on both parent and teacher dashboards. Needs to sort newest to oldest

**Comment by vilavlooi** [comment]
Discovered that this bug scope is much larger and more Critical than anticipated, it is causing notifications/treatments and evaluations to get "dropped" . It seems that in all cases "Alerts" seem to take precedent, then "evaluations", then "Notifications and treatments", in the event that the threshold of 10 is reached the lowest precedent types gets "dropped" on both the Parent and Teacher Dashboard, I think this bug is critical, as Treatments and notifications are not showing on the parents or teachers dashboard. Please can we fix this one as first priority. Let me know what I can do

**Comment by tb4mmaggots** [comment]
Except for current string dates, sorting seems to work correctly.
